(function () {
  'use strict';
  var languageCodeToNames = {
    'af': 'Afrikaans',
    'ar': 'Arabic',
    'ar_ae': 'Arabic (U.A.E.)',
    'ar_bh': 'Arabic (Bahrain)',
    'ar_dz': 'Arabic (Algeria)',
    'ar_eg': 'Arabic (Egypt)',
    'ar_iq': 'Arabic (Iraq)',
    'ar_jo': 'Arabic (Jordan)',
    'ar_kw': 'Arabic (Kuwait)',
    'ar_lb': 'Arabic (Lebanon)',
    'ar_ly': 'Arabic (Libya)',
    'ar_ma': 'Arabic (Morocco)',
    'ar_om': 'Arabic (Oman)',
    'ar_qa': 'Arabic (Qatar)',
    'ar_sa': 'Arabic (Saudi Arabia)',
    'ar_sy': 'Arabic (Syria)',
    'ar_tn': 'Arabic (Tunisia)',
    'ar_ye': 'Arabic (Yemen)',
    'az': 'Azeri (Latin)',
    'bs_ba': 'Bosnian (Bosnia and Herzegovina)',
    'be': 'Belarusian',
    'bg': 'Bulgarian',
    'ca': 'Catalan',
    'ca_es': 'Catalan (Spain)',
    'cs': 'Czech',
    'cs_cz': 'Czech (Czech Republic)',
    'da': 'Danish',
    'da_dk': 'Danish (Denmark)',
    'de': 'German (Standard)',
    'de_at': 'German (Austria)',
    'de_ch': 'German (Switzerland)',
    'de_li': 'German (Liechtenstein)',
    'de_lu': 'German (Luxembourg)',
    'el': 'Greek',
    'el_gr': 'Greek (Greece)',
    'en': 'English',
    'en_au': 'English (Australia)',
    'en_bz': 'English (Belize)',
    'en_ca': 'English (Canada)',
    'en_gb': 'English (United Kingdom)',
    'en_hk': 'English (Hong Kong)',
    'en_hu': 'English (Hungary)',
    'en_id': 'English (Indonesia)',
    'en_ie': 'English (Ireland)',
    'en_in': 'English (India)',
    'en_jm': 'English (Jamaica)',
    'en_kr': 'English (South Korea)',
    'en_mm': 'English (Myanmar)',
    'en_my': 'English (Malaysia)',
    'en_nz': 'English (New Zealand)',
    'en_sg': 'English (Singapore)',
    'en_tt': 'English (Trinidad)',
    'en_us': 'English (United States)',
    'en_za': 'English (South Africa)',
    'es': 'Spanish (Spain)',
    'es_ar': 'Spanish (Argentina)',
    'es_bo': 'Spanish (Bolivia)',
    'es_cl': 'Spanish (Chile)',
    'es_co': 'Spanish (Colombia)',
    'es_cr': 'Spanish (Costa Rica)',
    'es_do': 'Spanish (Dominican Republic)',
    'es_ec': 'Spanish (Ecuador)',
    'es_gt': 'Spanish (Guatemala)',
    'es_hn': 'Spanish (Honduras)',
    'es_mx': 'Spanish (Mexico)',
    'es_ni': 'Spanish (Nicaragua)',
    'es_pa': 'Spanish (Panama)',
    'es_pe': 'Spanish (Peru)',
    'en_ph': 'English (Philippines)',
    'es_pr': 'Spanish (Puerto Rico)',
    'es_py': 'Spanish (Paraguay)',
    'es_sv': 'Spanish (El Salvador)',
    'es_us': 'Spanish (United States)',
    'es_uy': 'Spanish (Uruguay)',
    'es_ve': 'Spanish (Venezuela)',
    'et': 'Estonian',
    'eu': 'Basque',
    'fa': 'Farsi',
    'fa_ir': 'Farsi (Iran)',
    'fi': 'Finnish',
    'fil_ph': 'Filipino (Philippines)',
    'fo': 'Faeroese',
    'fr': 'French (Standard)',
    'fr_be': 'French (Belgium)',
    'fr_ca': 'French (Canada)',
    'fr_ch': 'French (Switzerland)',
    'fr_lu': 'French (Luxembourg)',
    'ga': 'Irish',
    'gd': 'Gaelic (Scotland)',
    'he': 'Hebrew',
    'hi': 'Hindi',
    'hi_in': 'Hindi (India)',
    'hr': 'Croatian',
    'hu': 'Hungarian',
    'id': 'Indonesian',
    'is': 'Icelandic',
    'it': 'Italian (Standard)',
    'it_ch': 'Italian (Switzerland)',
    'iw_il': 'Hebrew',
    'ja': 'Japanese',
    'ja_jp': 'Japanese (Japan)',
    'ji': 'Yiddish',
    'ka_ge': 'Georgian (Georgia)',
    'kk_kz': 'Kazakh (Kazakhstan)',
    'km_kh': 'Khmer',
    'ko': 'Korean',
    'ko_an': 'Korean (Netherlands Antilles)',
    'ko_ca': 'Korean (Canada)',
    'ko_gb': 'Korean (Great Britain)',
    'ko_kp': 'Korean (North Korea)',
    'ko_kr': 'Korean (South Korea)',
    'ko_sd': 'Korean (Sudan)',
    'ko_so': 'Korean (Somalia)',
    'ko_st': 'Korean (Sao Tome and Principe)',
    'ko_tr': 'Korean (Turkey)',
    'ko_us': 'Korean (United States)',
    'kr': 'Kanuri',
    'kr_gb': 'Kanuri (Great Britain)',
    'kr_cn': 'Kanuri (China)',
    'ku': 'Kurdish',
    'lt': 'Lithuanian',
    'lv': 'Latvian',
    'mk': 'Macedonian (FYROM)',
    'ml': 'Malayalam',
    'ms': 'Malaysian',
    'ms_my': 'Malaysian (Malaysia)',
    'mt': 'Maltese',
    'nl': 'Dutch (Standard)',
    'nl_be': 'Dutch (Belgium)',
    'nb': 'Norwegian (Bokmål)',
    'nn': 'Norwegian (Nynorsk)',
    'no': 'Norwegian',
    'pa': 'Punjabi',
    'pl': 'Polish',
    'pt': 'Portuguese (Portugal)',
    'pt_br': 'Portuguese (Brazil)',
    'rm': 'Rhaeto-Romanic',
    'ro': 'Romanian',
    'ro_md': 'Romanian (Republic of Moldova)',
    'ru': 'Russian',
    'ru_md': 'Russian (Republic of Moldova)',
    'sb': 'Sorbian',
    'sk': 'Slovak',
    'sl': 'Slovenian',
    'sl_si': 'Slovenian (Slovenia)',
    'sq': 'Albanian',
    'sr': 'Serbian',
    'sr_rs': 'Serbian (Cyrillic)',
    'sv': 'Swedish',
    'sv_fi': 'Swedish (Finland)',
    'sv_se': 'Swedish (Sweden)',
    'th': 'Thai',
    'tn': 'Tswana',
    'tr': 'Turkish',
    'ts': 'Tsonga',
    'uk': 'Ukrainian',
    'uk_ua': 'Ukrainian (Ukraine)',
    'ur': 'Urdu',
    've': 'Venda',
    'vi': 'Vietnamese',
    'vi_vn': 'Vietnamese (Vietnam)',
    'xh': 'Xhosa',
    'zh_cn': 'Chinese (PRC)',
    'zh_hk': 'Chinese (Hong Kong)',
    'zh_sg': 'Chinese (Singapore)',
    'zh_tw': 'Chinese (Taiwan)',
    'zu': 'Zulu'
  };
  var langCult;
  function languageCodeFilter() {
    return function (input) {
      input = input.toLowerCase();
      langCult = input.split('_');
      if (langCult.length === 2 && langCult[0] === langCult[1]) {
        input = langCult[0];
      }
      if (languageCodeToNames[input]) {
        return languageCodeToNames[input];
      } else {
        return input;
      }
    };
  }
  angular.module('dataDashboard.common.filter.language', []).filter('language', languageCodeFilter);
}());